import * as THREE from './vendor/three.module.js';
const host=document.querySelector('.webgl-stage'),section=document.querySelector('.cinema'),portal=document.querySelector('.screen-portal');
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
let renderer;
try{renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance',alpha:true})}catch(e){document.documentElement.classList.add('webgl-fallback');console.warn('3D unavailable; photographic fallback enabled',e)}
if(renderer){
renderer.setPixelRatio(Math.min(devicePixelRatio,innerWidth<700?1.4:1.8));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;host.append(renderer.domElement);
const scene=new THREE.Scene();scene.background=new THREE.Color('#292a25');scene.fog=new THREE.Fog('#292a25',17,35);
const camera=new THREE.PerspectiveCamera(42,innerWidth/innerHeight,.025,65);
const material=(color,roughness=.5,metalness=0)=>new THREE.MeshStandardMaterial({color,roughness,metalness});
const walnut=material('#74472a',.36),silver=material('#bfc4cc',.28,.8),black=material('#12141a',.38),brass=material('#bca36c',.28,.75),wall=material('#8b8272',.8);
function woodTexture(){const c=document.createElement('canvas');c.width=2048;c.height=512;const ctx=c.getContext('2d');ctx.fillStyle='#74462c';ctx.fillRect(0,0,c.width,c.height);let seed=742;const rnd=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};for(let i=0;i<1600;i++){const y=rnd()*512;ctx.beginPath();ctx.moveTo(0,y);for(let x=0;x<=2048;x+=32)ctx.lineTo(x,y+Math.sin(x/200+i*.27)*(2+rnd()*5));ctx.strokeStyle=rnd()>.5?'rgba(34,14,5,.16)':'rgba(221,162,100,.11)';ctx.lineWidth=.3+rnd()*2;ctx.stroke()}for(let i=0;i<5;i++){ctx.fillStyle='#1e0e061a';ctx.fillRect(0,i*103,2048,2)}const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=renderer.capabilities.getMaxAnisotropy();return t}
walnut.map=woodTexture();walnut.needsUpdate=true;
function box(w,h,d,mat,x,y,z,shadow=true){const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);o.position.set(x,y,z);o.castShadow=shadow;o.receiveShadow=true;scene.add(o);return o}
function rounded(w,h,r){const s=new THREE.Shape();const x=-w/2,y=-h/2;s.moveTo(x+r,y);s.lineTo(x+w-r,y);s.quadraticCurveTo(x+w,y,x+w,y+r);s.lineTo(x+w,y+h-r);s.quadraticCurveTo(x+w,y+h,x+w-r,y+h);s.lineTo(x+r,y+h);s.quadraticCurveTo(x,y+h,x,y+h-r);s.lineTo(x,y+r);s.quadraticCurveTo(x,y,x+r,y);return s}
function slab(w,h,depth,r,mat){const geo=new THREE.ExtrudeGeometry(rounded(w,h,r),{depth,bevelEnabled:true,bevelSegments:3,steps:1,bevelSize:.015,bevelThickness:.01,curveSegments:12});geo.translate(0,0,-depth/2);const m=new THREE.Mesh(geo,mat);m.castShadow=true;m.receiveShadow=true;return m}
// Architecture, desk, warm practical lights.
box(13,.2,8,walnut,0,-.18,0);box(.22,2.5,6,black,-5,-1.5,0);box(.22,2.5,6,black,5,-1.5,0);
box(19,11,.2,wall,0,3,-5.8);box(.2,11,17,wall,8,3,0);box(20,.2,18,material('#423d34',.85),0,-3,0);
for(let i=0;i<14;i++)box(.07,8,.12,material('#746348',.7),-7+i*1.07,3,-5.64,false);
const windowMat=new THREE.MeshBasicMaterial({color:'#c6d9df'});box(.12,6,5.6,windowMat,-7,3,-2,false);for(let i=0;i<4;i++)box(.18,6,.07,black,-6.91,3,-4.6+i*1.7,false);
box(1.7,.09,1.1,material('#d4c8ac',.6),-3.6,.01,-.7).rotation.y=.12;box(1.65,.07,1.05,material('#35281e',.8),-3.65,.11,-.7).rotation.y=.12;
const lamp=new THREE.Mesh(new THREE.CylinderGeometry(.045,.045,2.4,24),brass);lamp.position.set(3.8,1.18,-1);scene.add(lamp);const base=new THREE.Mesh(new THREE.CylinderGeometry(.6,.64,.06,48),brass);base.position.set(3.8,.01,-1);scene.add(base);const shade=new THREE.Mesh(new THREE.SphereGeometry(.72,48,24,0,Math.PI*2,0,Math.PI/2),brass);shade.position.set(3.8,2.5,-1);scene.add(shade);
const lampLight=new THREE.PointLight('#ffce87',28,9,2);lampLight.position.set(3.8,2.2,-1);scene.add(lampLight);
scene.add(new THREE.HemisphereLight('#e5ecf2','#493323',2.3));const sunlight=new THREE.DirectionalLight('#ffe3bd',5);sunlight.position.set(-5,8,4);sunlight.castShadow=true;sunlight.shadow.mapSize.set(2048,2048);sunlight.shadow.camera.left=-9;sunlight.shadow.camera.right=9;sunlight.shadow.camera.top=8;sunlight.shadow.camera.bottom=-8;sunlight.shadow.normalBias=.025;sunlight.shadow.bias=-.0002;sunlight.shadow.radius=4;scene.add(sunlight);
// Laptop is fixed to the desk; only the camera moves.
const laptop=new THREE.Group();scene.add(laptop);const deck=slab(3.7,2.35,.08,.12,silver);deck.rotation.x=-Math.PI/2;deck.position.set(0,.015,.94);laptop.add(deck);
const keyboard=slab(3.16,1.16,.025,.06,black);keyboard.rotation.x=-Math.PI/2;keyboard.position.set(0,.073,.64);laptop.add(keyboard);
for(let row=0;row<5;row++)for(let col=0;col<14;col++){const key=slab(.18,.155,.012,.02,material('#202329',.48));key.rotation.x=-Math.PI/2;key.position.set(-1.45+col*.223,.093,.22+row*.214);laptop.add(key)}
const track=slab(1.18,.58,.008,.035,material('#aeb4be',.4,.6));track.rotation.x=-Math.PI/2;track.position.set(0,.071,1.68);laptop.add(track);
const lid=slab(3.68,2.35,.06,.1,silver);lid.position.set(0,1.25,-.17);laptop.add(lid);
const bezel=slab(3.51,2.19,.009,.06,black);bezel.position.set(0,1.27,-.127);laptop.add(bezel);
const screenCenter=new THREE.Vector3(0,1.27,-.105);
function screenTexture(){const c=document.createElement('canvas');c.width=1600;c.height=1000;const x=c.getContext('2d');x.fillStyle='#f4f3ef';x.fillRect(0,0,1600,1000);x.fillStyle='#111';x.font='bold 20px Arial';x.fillText('AI SYSTEMS  /  PRODUCT DEMO',65,58);x.fillStyle='#777';x.font='16px Arial';x.fillText('A conversation. A qualified enquiry.',1050,58);x.fillStyle='#080808';x.beginPath();x.roundRect(340,180,560,690,26);x.fill();x.fillStyle='#fff';x.font='bold 22px Arial';x.fillText('AI ASSISTANT',380,237);x.fillStyle='#c5b48f';x.beginPath();x.arc(370,268,5,0,7);x.fill();x.font='14px Arial';x.fillText('ONLINE',390,274);x.fillStyle='#252525';x.beginPath();x.roundRect(380,330,400,78,14);x.fill();x.fillStyle='#eee';x.font='19px Arial';x.fillText('Hi. How can I help you today?',400,375);x.strokeStyle='#333';x.strokeRect(380,764,470,62);x.fillStyle='#888';x.font='16px Arial';x.fillText('Type your message',400,801);x.fillStyle='#fff';x.beginPath();x.roundRect(965,340,350,370,24);x.fill();x.fillStyle='#897047';x.font='bold 15px Arial';x.fillText('YOUR NEXT ENQUIRY',995,382);x.fillStyle='#111';x.font='bold 27px Arial';x.fillText('Ready for your team.',995,435);x.fillStyle='#888';x.font='18px Arial';x.fillText('Service · Location · Contact',995,485);x.fillText('Captured in one conversation.',995,526);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t}
const screen=new THREE.Mesh(new THREE.PlaneGeometry(3.35,2.08),new THREE.MeshBasicMaterial({map:screenTexture(),toneMapped:false}));screen.position.copy(screenCenter);laptop.add(screen);
const lens=new THREE.Mesh(new THREE.SphereGeometry(.016,16,8),material('#314054',.15,.4));lens.position.set(0,2.36,-.107);laptop.add(lens);
let start=performance.now(),active=true,p=0;const smooth=t=>t*t*(3-2*t);const top=new THREE.Vector3(.7,9,1.4),wide=new THREE.Vector3(4.6,4.5,6.8),front=new THREE.Vector3(0,1.27,3.7);const look=new THREE.Vector3();
function resize(){renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}addEventListener('resize',resize);
function progress(){const r=section.getBoundingClientRect();p=Math.max(0,Math.min(1,-r.top/(section.offsetHeight-innerHeight)))}addEventListener('scroll',progress,{passive:true});progress();
function frame(now){requestAnimationFrame(frame);if(!active)return;const intro=reduced?1:smooth(Math.min(1,(now-start)/4200));const travel=smooth(Math.min(1,p/.72));const resting=top.clone().lerp(wide,intro);const fitDistance=Math.max(2.08/(2*Math.tan(THREE.MathUtils.degToRad(21))),3.35/(2*Math.tan(THREE.MathUtils.degToRad(21))*camera.aspect));front.z=screenCenter.z+fitDistance*.94;camera.position.copy(resting).lerp(front,travel);look.set(0,.55,0).lerp(screenCenter,travel);camera.lookAt(look);const handoff=smooth(Math.max(0,Math.min(1,(p-.64)/.13)));portal.style.opacity=handoff;portal.style.visibility=handoff>.01?'visible':'hidden';host.style.opacity=1-handoff;section.style.setProperty('--copy',Math.max(0,1-p*5));document.querySelector('.photo-camera').style.opacity='0';if(p>.76&&window.startCinematicChat)window.startCinematicChat();renderer.render(scene,camera)}
new IntersectionObserver(es=>{active=es[0].isIntersecting},{rootMargin:'100px'}).observe(section);requestAnimationFrame(frame);
}
